### PR TITLE
V9.0.0/lock refactoring

### PR DESCRIPTION
**Pull request by gimlichael**
#### PR Classification
New feature and dependency update to support .NET 9 and backport `System.Threading.Lock`.

#### PR Summary
Updated package to support .NET 9 and added backport for `System.Threading.Lock` for earlier TFMs.
- `PackageReleaseNotes.txt`: Version updated to 9.0.0 with new .NET support.
- `Cuemon.Core.csproj`: Removed conditional compilation of `Threading\Lock.cs` for .NET 9.0.
- `Dependency.cs` and related files: Replaced `Lock` object with standard `object` for locking.
- `Lock.cs`: Removed backport of .NET 9.0's `System.Threading.Lock`.
- `Cuemon.Extensions.Threading.csproj`: Added package reference to `Backport.System.Threading.Lock`.

This PR is a result of this good discussion in prev. PR https://github.com/gimlichael/Cuemon/pull/73#issuecomment-2338984067

## Summary by CodeRabbit

- **New Features**
  - Major version update to 9.0.0, now supporting .NET 9, .NET 8, .NET 6, and .NET Standard 2.0.
  - Introduced support for the `System.Threading.Lock` object for .NET versions prior to 9.0.

- **Bug Fixes**
  - Enhanced synchronization mechanisms across various classes by changing locking types from `Lock` to a more generic `object`.

- **Documentation**
  - Updated release notes and changelog to reflect new features and changes in compatibility.

- **Chores**
  - Updated project files to include necessary package references and conditional imports for improved threading capabilities.

### CODE REVIEW

**Comment by gimlichael** [comment]
@MarkCiliaVincenti feel free to review.

**Comment by MarkCiliaVincenti** [comment]
Will take a look in about 12 hours if that works for you :)

**Comment by MarkCiliaVincenti** [comment]
I'm not sure what you did here Michael.

Let me bring an example.
[Cuemon.Extensions.AspNetCore.Newtonsoft.Json](https://github.com/gimlichael/Cuemon/tree/v9.0.0/lock-refactoring/src/Cuemon.Extensions.AspNetCore.Newtonsoft.Json) targets frameworks net6.0, net8.0 and net9.0. Therefore this code in this assembly does not need to use the factory method. You can just create instances of System.Threading.Lock if the library is referenced, even transitively. So in https://github.com/gimlichael/Cuemon/blob/v9.0.0/lock-refactoring/src/Cuemon.Extensions.AspNetCore.Newtonsoft.Json/Bootstrapper.cs you should have `private static readonly Lock PadLock = new();`

**Comment by gimlichael** [comment]
> I'm not sure what you did here Michael.
> 
> Let me bring an example. [Cuemon.Extensions.AspNetCore.Newtonsoft.Json](https://github.com/gimlichael/Cuemon/tree/v9.0.0/lock-refactoring/src/Cuemon.Extensions.AspNetCore.Newtonsoft.Json) targets frameworks net6.0, net8.0 and net9.0. Therefore this code in this assembly does not need to use the factory method. You can just create instances of System.Threading.Lock if the library is referenced, even transitively. So in https://github.com/gimlichael/Cuemon/blob/v9.0.0/lock-refactoring/src/Cuemon.Extensions.AspNetCore.Newtonsoft.Json/Bootstrapper.cs you should have `private static readonly Lock PadLock = new();`

I get what you are writing - but I also only want todo a min. of dependencies - also to avoid the risk of circular references.
Personally I don't see an advantage with the new Lock class vs. new object for something as simple as the bootstrapper.
That written - I do acknowledge that more sophisticated use-cases exists and this Lock class will prove useful.

With these changes - although not utilized directly within Cuemon - your library is referenced in the confines of Cuemon.Extensions.Threading (which is a suitable place for 3rd party dependencies).

**Comment by MarkCiliaVincenti** [comment]
Up to you as long as you understand the pros and cons. I didn't get into nitty gritty details of what the code does where and if it later becomes a hot path how you can easily help some optimisation through the locking.

If you have any questions now or later don't hesitate to ask.

Let's go!

**Pull request merged**
