### PR TITLE
Improved performance for .NET 9.0+ through System.Threading.Lock.

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Lock` class for enhanced thread safety and synchronization across various components.
	- Updated locking mechanisms in multiple classes to utilize the new `Lock` type, improving concurrency control.

- **Bug Fixes**
	- Improved thread safety in classes such as `FileWatcher`, `DatabaseWatcher`, and `Bootstrapper` through refined locking strategies.

- **Documentation**
	- Updated documentation to reflect changes in locking mechanisms and their benefits for concurrency management.

### CODE REVIEW

**Comment by gimlichael** [comment]
Thank you for your contribution - I will review it and might add-in some preprocessor-directives for backward compatibility.

**Comment by MarkCiliaVincenti** [comment]
Hi,

You don't really need any preprpcessor directives. The micro dependency added takes care of that. Furthermore, the dependency is only added for frameworks earlier than .NET 9.0

**Comment by gimlichael** [comment]
I like your proposed changes - but since Cuemon extends upon Microsoft .NET, one rule is to not have dependencies to other assemblies. Unless they are explicit made so, e.g., :

- Cuemon.Extensions.Newtonsoft.Json
- Cuemon.Extensions.Swashbuckle.AspNetCore
- Cuemon.Extensions.Xunit
- Cuemon.Extensions.YamlDotNet

So unless you feel for it, this PR can only be merged without external dependency, hence only be made available for .NET 9.

BTW; cool little library you have written - kudos!

**Comment by MarkCiliaVincenti** [comment]
I understand, though it is hardly a dependency in the sense that it is merely making calls to methods that are part of the framework.

It is MIT though so you can copy in the single class file, although credit to the library would be appreciated. You'll miss out on potential updates though this way.

**Comment by gimlichael** [comment]
I will consider it for sure - and credits are self-evident. Thank you for your understanding.

**Comment by MarkCiliaVincenti** [comment]
> I will consider it for sure - and credits are self-evident. Thank you for your understanding.

Check now.

**Comment by MarkCiliaVincenti** [comment]
@gimlichael note that on .NET 9.0+, the added class will even be excluded from compilation.

**Comment by gimlichael** [comment]
Could be - since the attribute only affects .NET Framework .. and looks like an escalation of privilege.
Its been a while since I have looked at these specialized attributes in .NET Framework context .. I can try to remove it after the test-run complete .. so far 22 failed tests. Hooray for tests!

**Comment by MarkCiliaVincenti** [comment]
This worries me because I did add that attribute to my library because
someone's library was throwing that exception. I had never used these
before so now I'm wondering if it's something like async where you have to
go "all the way", in which case it would be a problem for the library.

Regards,

Mark Cilia Vincenti

**Comment by gimlichael** [comment]
That is a good point - and sometime in .NET Framework context extra privilege might be granted. If I have more energy tomorrow, I will try to poke around as it has awaken my curiosity.

Btw; when I removed the attribute, the tests passes ✅

**Comment by MarkCiliaVincenti** [comment]
Very interesting. I'm trying to play around but perhaps not a good idea to use an 11 year old laptop.

Thing is, forget this PR... what happens if an assembly tries to use Cuemon with extra privileges? Will it complain?

**Comment by gimlichael** [comment]
That would probably be a use-case to play around with. The original source is from Microsoft: https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/Extensions/NonCapturingTimer/NonCapturingTimer.cs which is used by a number of assembly packages that also targets .NET Framework. Interestingly, they have not decorated anywhere with `[SecuritySafeCritical]` which Copilot suggest might be a solution. Then again; this was the "old" way with object as a PadLock.

---

The error message you're encountering is related to .NET's security model, specifically around the concept of security transparency. Here's a breakdown of the key components:

**Security Transparency**

•	Security Transparent Methods: These methods cannot perform security-critical operations. They are considered safe and cannot elevate privileges or access sensitive resources.
•	Security Critical Methods: These methods can perform operations that require elevated privileges and can access sensitive resources.

**The Error**

The error message indicates that a security transparent method (Cuemon.Threading.TimerFactory.CreateNonCapturingTimer) is attempting to call a security critical method (System.Threading.ExecutionContext.SuppressFlow). This is not allowed under .NET's security model.

**Why This Happens**

•	Security Transparent Code: The method CreateNonCapturingTimer is marked as security transparent, meaning it should not perform any security-sensitive operations.
•	Security Critical Code: The method SuppressFlow is marked as security critical, meaning it performs operations that require higher privileges.

**How to Resolve**

1.	Review Method Attributes: Ensure that the method CreateNonCapturingTimer is correctly marked with the appropriate security attributes. If it needs to call security critical methods, it should be marked as security critical or security safe-critical.
2.	Refactor Code: If possible, refactor the code to avoid calling security critical methods from security transparent methods.
3.	Update Security Policies: Ensure that your project’s security policies and attributes are correctly configured to allow the necessary operations.

**Comment by MarkCiliaVincenti** [comment]
How do you want to do this? Do you want to:

a) remove that attribute from Lock.cs
or
b) re-add the dependency to Backport.System.Threading.Lock?

Either way allow those tests to work successfully. Option B sounds safer to me, but you had some reservations about adding in a new dependency.

Let me know and I'll amend the PR accordingly.

**Comment by gimlichael** [comment]
I need to sleep on it, but for sure no dependency from the core assembly. I might tweak for legacy .NET Framework.

**Comment by MarkCiliaVincenti** [comment]
Not sure what you mean, something like this?

<ItemGroup Condition="'$(TargetFramework)' == 'net45'">
  <PackageReference Include="Backport.System.Threading.Lock" Version="1.1.6" />
  <Compile Remove="Threading\Lock.cs" />
</ItemGroup>

That condition is probably wrong.

**Comment by MarkCiliaVincenti** [comment]
But then you can't call the methods available on System.Threading.Lock. In fact, you'd only be able to use lock (syncRoot), nothing else. You can't even use Monitor.Enter on a Lock object, that's why it exposes its own Enter method for example.

**Comment by MarkCiliaVincenti** [comment]
Another option to consider is to create a new project called Backport.System.Threading.Lock and literally copy everything in there rather than rely on a Lock.cs in the same assembly. It would also be easier to update in case of changes. As long as you credit it, I'm fine with that as well.

**Comment by gimlichael** [comment]
Correct, but for legacy .NET I think backward compatibility is more important. Cuemon was originally NET Framework 2 and 4 CLR additions, that then matured almost purely to .NET (core). However, many assemblies still work with net48 and netstandard2.0.

**Comment by MarkCiliaVincenti** [comment]
> Correct, but for legacy .NET I think backward compatibility is more important. Cuemon was originally NET Framework 2 and 4 CLR additions, that then matured almost purely to .NET (core). However, many assemblies still work with net48 and netstandard2.0.

I understand, but are there any scenarios where having Backport.System.Threading.Lock as a project in your solution give any issues under net48 or earlier? I fiddled around with different scenarios and I couldn't find any issue.

Are your concerns borne out of "just in case" or is there an actual issue? I'm asking because if there is I'd obviously like to fix it.

**Comment by gimlichael** [comment]
Its more a principle than a concern. As mentioned earlier, exceptions are though that outside of the confines of Microsoft, where I add a Cuemon.Extensions.3rdParty .. at work now .. will get back .. .NET is more important than .NET Legacy ..  haha .. that is why I think the safer approach is simply having an empty class - otherwise the changes will be to vast, I think.

**Comment by gimlichael** [comment]
@MarkCiliaVincenti I have researched a little further. I think you just need to :remove SecurityTransparent attribute as this should not apply to the Cuemon.Core assembly: https://learn.microsoft.com/en-us/dotnet/api/system.security.securitytransparentattribute

Then it should be good to go.

**Comment by MarkCiliaVincenti** [comment]
Done.

**Comment by gimlichael** [comment]
Apologies, but could you update your fork with the last two commits? The latest one fixes a security related feature, that should allow my CI to run using pull_request_target instead of pull_request trigger. Sorry for the inconvenience. More info.: https://www.codu.co/articles/when-to-use-pull_request_target-instead-of-pull_request-in-github-actions-k3pao1qz

**Comment by MarkCiliaVincenti** [comment]
Synced fork

**Comment by MarkCiliaVincenti** [comment]
These failures look unrelated, right?

**Comment by gimlichael** [comment]
Merged - thank you for your contribution!

**Comment by MarkCiliaVincenti** [comment]
Hi @gimlichael, I have become aware that the lock implementation was not hardened against thread aborts. Given that you are targeting netstandard2.0 it means you are affected. On pre-.NET 5.0, someone could call a Thread.Abort() at a very short time window between when the lock is obtained and it entering a try lock, leaving the lock object in a locked state.

I suggest you go for these files instead:
https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/master/Backport.System.Threading.Lock/LockFactory.cs
https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/master/Backport.System.Threading.Lock/PreNet5Lock.cs

and then you can have this in your csproj files or Directory.Build.props:
```
<ItemGroup>
  <Using Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="System.Threading.Lock" />
  <Using Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="Backport.System.Threading.Lock" />
  <Using Alias="LockFactory" Include="Backport.System.Threading.LockFactory" />
</ItemGroup>
```

**Comment by MarkCiliaVincenti** [comment]
You would then need to change from `new Lock()` to `LockFactory.Create()`

**Comment by gimlichael** [comment]
> Hi @gimlichael, I have become aware that the lock implementation was not hardened against thread aborts. Given that you are targeting netstandard2.0 it means you are affected. On pre-.NET 5.0, someone could call a Thread.Abort() at a very short time window between when the lock is obtained and it entering a try lock, leaving the lock object in a locked state.
> 
> I suggest you go for these files instead: https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/master/Backport.System.Threading.Lock/LockFactory.cs https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/master/Backport.System.Threading.Lock/PreNet5Lock.cs
> 
> and then you can have this in your csproj files or Directory.Build.props:
> 
> ```
> <ItemGroup>
>   <Using Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="System.Threading.Lock" />
>   <Using Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="Backport.System.Threading.Lock" />
>   <Using Alias="LockFactory" Include="Backport.System.Threading.LockFactory" />
> </ItemGroup>
> ```

@MarkCiliaVincenti - to keep things simple - would this fix work: https://github.com/gimlichael/Cuemon/blob/v9.0.0/lock-refactoring/src/Cuemon.Core/Threading/Lock.cs

If not, then I will remove the `#else` and update those assemblies that targets `netstandard2.0` to use new object (as before) and simply only provide Lock surrogate for >= NET5.0 && <= .NET8.0.

Thoughts?

**Comment by MarkCiliaVincenti** [comment]
I'm not convinced. I will take a look tomorrow. But would you consider putting it into its own project? I think it would be much simpler if you do especially if the library undergoes more changes in future. Certain things need to be done with caution like the use of that type forwarding for example.

**Comment by MarkCiliaVincenti** [comment]
Also not sure what you meant re targets. If you only target net5 and above it would be simpler yes. You can also do without the type forwarding as long as you do target net9 directly as well.

**Comment by gimlichael** [comment]
> I'm not convinced. I will take a look tomorrow. But would you consider putting it into its own project? I think it would be much simpler if you do especially if the library undergoes more changes in future. Certain things need to be done with caution like the use of that type forwarding for example.

That might be a good idea; I do have https://github.com/gimlichael/Cuemon/tree/main/src/Cuemon.Threading that might be a good fit for this addition. As you allude to, it might be a cleaner cut .. still not able to reference your library directly, but the maintenance would be moved from "core" to "complemental".

That written .. if the proposal seems to work, maybe its good enough?
Only reason I was hesitant was due to your factory implementation and writing in the notes that this class should not be instantiated on its own .. but I figure that is due to the factory, which I skipped in favor of a more "clean" though redundant implementation.

**Comment by MarkCiliaVincenti** [comment]
Because of the TypeForwardedTo it should be in its own assembly.

Basically in something that's .NET 5.0+ you can do this (replace PackageReference with ProjectReference if you don't want to depend on the library):

```
<ItemGroup>
  <PackageReference Include="Backport.System.Threading.Lock" Version="2.0.0" />
  <Using Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="System.Threading.Lock" />
  <Using Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="Backport.System.Threading.Lock" />
  <Using Alias="LockFactory" Include="Backport.System.Threading.LockFactory" />
</ItemGroup>

...

private readonly Lock _syncRoot = LockFactory.Create();
```

and if using something that targets anything prior to .NET 5.0:

```
<ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">
  <PackageReference Include="Backport.System.Threading.Lock" Version="2.0.0" />  
</ItemGroup>

...

private readonly Lock _syncRoot = new();
```

Up to you whichever way you want to take this.

**Comment by MarkCiliaVincenti** [comment]
Because of the TypeForwardedTo (AssemblyInfo.cs) it should be in its own assembly.

Basically in something that's .NET 5.0+ you can do this (replace PackageReference with ProjectReference if you don't want to depend on the library):

```
<ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">
  <PackageReference Include="Backport.System.Threading.Lock" Version="2.0.0" />  
</ItemGroup>

...

private readonly Lock _syncRoot = new();
```

and if using something that targets anything prior to .NET 5.0:

```
<ItemGroup>
  <PackageReference Include="Backport.System.Threading.Lock" Version="2.0.0" />
  <Using Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="System.Threading.Lock" />
  <Using Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="Backport.System.Threading.Lock" />
  <Using Alias="LockFactory" Include="Backport.System.Threading.LockFactory" />
</ItemGroup>

...

private readonly Lock _syncRoot = LockFactory.Create();
```

Up to you whichever way you want to take this.

**Comment by gimlichael** [comment]
> TypeForwardedTo

I will reference your assembly in a hidden gem of mine; Cuemon.Extensions.Threading. If possible, I would encourage you to see if its possible to skip the LockFactory.Create() for consistency. That said; this option does not violate principles of Cuemon - and it embraces your library extension for .NET.

I will make a PR later that you are welcome to approve.

**Comment by MarkCiliaVincenti** [comment]
The reason for LockFactory.Create() is that it is dangerous to provide an instance called System.Threading.Lock to pre .NET 5.0, because when you lock on it, on a .NET 8 or .NET 9 compiler it will end up compiling the code in a way that is not hardened against thread aborts; basically if a thread is aborted exactly after it obtains a lock and before it starts doing whatever needs to happen inside the lock, it would leave the lock object locked.

LockFactory.Create() is there so that if you're on .NET 9.0+ you get System.Threading.Lock and if you're anything before that you get an instance of a Backport.System.Threading.Lock, which means that the compiler will compile pre .NET 5.0 code in a way that is hardened against thread aborts.

**Pull request merged**
